CREATE DATABASE QLXEMAY
USE QLXEMAY

 ---TAO BANG XE---
CREATE TABLE XE( MAXE NVARCHAR(50) PRIMARY KEY(MAXE), TENXE NVARCHAR(100),NHASANXUAT NVARCHAR(100), SOLUONG INT,THONGTINBAOHANH NVARCHAR(100),GIA INT,MOTA NVARCHAR(200));
 ---TAO BANG NHA CUNG CAP---
 CREATE TABLE NHACUNGCAP(MANHACC NVARCHAR(50) PRIMARY KEY(MANHACC),TENNCC NVARCHAR(100),DIACHI NVARCHAR(100));
 ---TAO BANG KHACH HANG ---
 CREATE TABLE KHACHHANG(MAKH NVARCHAR(50) PRIMARY KEY(MAKH),TENKH NVARCHAR(100),DIACHI NVARCHAR(100),SDT NVARCHAR(50));
 ---GAO BANG NHAN VIEN---
 CREATE TABLE NHANVIEN(MANV NVARCHAR(50) PRIMARY KEY(MANV),TENNV NVARCHAR(100),NGAYSINH DATETIME,GIOITINH NVARCHAR(10),DIACHI NVARCHAR(100),SDT NVARCHAR(50),CHUCVU NVARCHAR(50),LUONG INT);
 ---TAO BANG NHAP---
 CREATE TABLE PHIEUNHAP(MAPN NVARCHAR(50) PRIMARY KEY(MAPN),NGAYNHAP DATETIME,MA_NV NVARCHAR(50),MA_NHACC NVARCHAR(50) 
 ---TAO BANG CHI TIET PHIEU NHAP---
 CREATE TABLE CHITIETPHIEUNHAP(MAPN NVARCHAR(50),MAHANG NVARCHAR(50),SOLUONG INT,DONGIA INT,THUE FLOAT,PRIMARY KEY(MAPN,MAHANG));
 ----TAO BANG XUAT---
 CREATE TABLE PHIEUXUAT(MAPX NVARCHAR(50) PRIMARY KEY(MAPX),NGAYXUAT DATETIME,MA_NV NVARCHAR(50),MA_KH NVARCHAR(50));
 ---TAO BANG PHIEU XUAT---
 CREATE TABLE CHITIETPHIEUXUAT(MAPX NVARCHAR(50),MAHANG NVARCHAR(50),SOLUONG INT,DONGIA INT,THUE FLOAT,PRIMARY KEY(MAPX,MAHANG));
 --- NHAP LIEU---
 INSERT INTO XE (MAXE,TENXE,NHASANXUAT,SOLUONG,THONGTINBAOHANH,GIA,MOTA) VALUES ('EX','Exciter','Yamaha',10,'3 nam',1000000,'');
 INSERT INTO XE (MAXE,TENXE,NHASANXUAT,SOLUONG,THONGTINBAOHANH,GIA,MOTA) VALUES ('SR','Sirius','Yamaha',20,'1 nam',1500000,'');


 INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,SDT) VALUES ('KH01','Tai','Tp.HCM','');
 ---TAO KHOA NGOAI---
 ALTER TABLE PHIEUNHAP 
 ADD CONSTRAINT PN_MA 
 FOREIGN KEY (MA_NV)
 REFERENCES NHANVIEN(MANV)

 ALTER TABLE PHIEUNHAP
 ADD CONSTRAINT PN_NHACC 
 FOREIGN KEY (MA_NHACC)
 REFERENCES  NHACUNGCAP(MANHACC)

 ALTER TABLE PHIEUXUAT
 ADD CONSTRAINT PX_MA 
 FOREIGN KEY (MA_NV)
 REFERENCES  NHANVIEN(MANV)

 ALTER TABLE PHIEUXUAT
 ADD CONSTRAINT PX_NHACC 
 FOREIGN KEY (MA_KH)
 REFERENCES KHACHHANG(MAKH)
 ---XOA KHOA NGOAI---
 ALTER TABLE PHIEUXUAT DROP PX_NHACC 
 ALTER TABLE PHIEUXUAT DROP PX_MA 
 ALTER TABLE PHIEUNHAP DROP PN_MA 
 ALTER TABLE PHIEUNHAP DROP PN_NHACC  
 ---XOA BANG---
 DROP TABLE XE
 DROP TABLE NHACUNGCAP
 DROP TABLE KHACHHANG
 DROP TABLE NHANVIEN
 DROP TABLE PHIEUNHAP
 DROP TABLE PHIEUXUAT
 DROP TABLE CHITIETPHIEUNHAP
 DROP TABLE CHITIETPHIEUXUAT